// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXSesVcKuGjxlyM3Mb2FLbW7pWI8L9Iws',
    appId: '1:339464481865:web:cae0d934b8b844e653e398',
    messagingSenderId: '339464481865',
    projectId: 'my-portfolio-280a8',
    authDomain: 'my-portfolio-280a8.firebaseapp.com',
    storageBucket: 'my-portfolio-280a8.firebasestorage.app',
    measurementId: 'G-3ZEJ3GZLHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqfk__gymF6DV77IXIE47LsyO7DaVvfB4',
    appId: '1:339464481865:android:f71cebe99dd6aa2e53e398',
    messagingSenderId: '339464481865',
    projectId: 'my-portfolio-280a8',
    storageBucket: 'my-portfolio-280a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTicNkAR8zG1M7oWCtMcT4CljXLYU-l_k',
    appId: '1:339464481865:ios:ee66b02cf6b30e6c53e398',
    messagingSenderId: '339464481865',
    projectId: 'my-portfolio-280a8',
    storageBucket: 'my-portfolio-280a8.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTicNkAR8zG1M7oWCtMcT4CljXLYU-l_k',
    appId: '1:339464481865:ios:ee66b02cf6b30e6c53e398',
    messagingSenderId: '339464481865',
    projectId: 'my-portfolio-280a8',
    storageBucket: 'my-portfolio-280a8.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXSesVcKuGjxlyM3Mb2FLbW7pWI8L9Iws',
    appId: '1:339464481865:web:2d812e41f5eb442e53e398',
    messagingSenderId: '339464481865',
    projectId: 'my-portfolio-280a8',
    authDomain: 'my-portfolio-280a8.firebaseapp.com',
    storageBucket: 'my-portfolio-280a8.firebasestorage.app',
    measurementId: 'G-QTFBES5S0S',
  );
}
